dist: trusty
language: shell

services:
  - docker

env:
  jobs:
    - TYPO3_VERSION=^10.4 PHP_VERSION=7.2
    - TYPO3_VERSION=^10.4 PHP_VERSION=7.4
    - TYPO3_VERSION=^9.5 PHP_VERSION=7.2
    - TYPO3_VERSION=^9.5 PHP_VERSION=7.4
    - TYPO3_VERSION=^8.7 PHP_VERSION=7.2
    - TYPO3_VERSION=^8.7 PHP_VERSION=7.4

script:
  - docker-compose run --rm app composer build

after_script:
  - docker-compose down --volumes
