version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.2}-v4-fpm
    environment:
      TYPO3_VERSION: ${TYPO3_VERSION:-^9.5}
      typo3DatabaseHost: mysql
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
      ELASTICSEARCH_HOST: elasticsearch:9200
      HTTP_HOST: dummy
    depends_on:
      - elasticsearch
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql

  elasticsearch:
    image: elasticsearch:5
