name: CI

on:
  push:
    branches:
     - master
     - elasticsearch7
    tags:
      - '*'
  pull_request:
    branches:
     - master
     - elasticsearch7
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.4
        typo3:
          - ^10.4
          - ^9.5

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
        run: docker-compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker-compose down --volumes
